### ISSUE TITLE
TonSafe violates Tonhub intellectual rights

### ISSUE THREAD

**Issue by dvlkv** [ton-blockchain/wallets-list#13]
## TonSafe based on Tonhub
TonSafe violates Tonhub GPL license with restrictions for App Store & Google Play distributions.

TonSafe has a same features that Tonhub has: 
- Onboarding flow exactly the same
- Contacts
- Hidden tokens
- tonhub dapp connectors (ton-x) 
- Same main page design

### Onboarding flow
<p align="left">
<img height="844" width="400" src="https://user-images.githubusercontent.com/16834309/221773323-9281e19c-6aba-4784-8a9b-588d26e5ef48.gif">
<img height="844" width="400" src="https://user-images.githubusercontent.com/16834309/221773374-67738843-3c76-47ef-bf21-383d09e37262.gif">
</p>

### Same screens
<p align="left">
<img width="400" alt="Screenshot 2023-02-27 at 6 01 49 PM" src="https://user-images.githubusercontent.com/16834309/221775532-d565f942-0424-4824-9e7f-d5390cbb3fe7.png">
<img width="400" alt="Screenshot 2023-02-27 at 6 01 49 PM" src="https://user-images.githubusercontent.com/16834309/221775816-ac239b97-9a4e-4ee2-a951-67bf4f302197.PNG">
</p>

<p align="left">
<img width="400" alt="Screenshot 2023-02-28 at 11 00 34 AM" src="https://user-images.githubusercontent.com/16834309/221778521-c08ac0ac-e02d-41c3-9a6c-1b655912d4cf.png">
<img width="400" alt="Screenshot 2023-02-28 at 11 00 34 AM" src="https://user-images.githubusercontent.com/16834309/221778491-c7e5da62-eb7a-4d3c-8212-a5c52504b402.PNG">
</p>

<p align="left">
<img width="400" alt="Screenshot 2023-02-28 at 10 59 56 AM" src="https://user-images.githubusercontent.com/16834309/221778799-eab5db27-4bb7-4af9-bc99-8aa5d9118860.png">
<img width="400" alt="Screenshot 2023-02-28 at 11 00 34 AM" src="https://user-images.githubusercontent.com/16834309/221778837-a5a97bb8-31a9-485e-8acb-c6396c2fec57.PNG">
</p>

### Uses Tonhub APIs
![tonsafe2](https://user-images.githubusercontent.com/16834309/221783017-009e8489-481d-471e-87e3-7d826172f21d.gif)

**Comment by tolya-yanot** [comment]
@tonsafe what do you think about it?

**Comment by tonsafe** [comment]
Thank you for your concerns @tolya-yanot 
We have published our response on this [blog post](https://blog.tonbase.net/tonhub).

**Comment by dvlkv** [comment]
@tonsafe so, you agree that TonSafe is based on Tonhub? If a current version is not based on it, you can make it open source to really prove that it is so, right?

Quote from article: 
`During this early stage of research the Tonhub code was forked, investigated, and initially used in early development but then a decision was made not to go open source for the foreseeable future, and so the Tonhub code was left behind. Any remnants from that early iteration are being progressively removed.
`

**Comment by vzhovnitsky** [comment]
@tonsafe 
Absolutely no evidence, twisting the facts. At the moment, right now, as one of the Tonhub developers, just see big chunks of the app that are identical copies of our app, EVEN with the same bugs that only I know about! And yet you have the audacity to talk about some of the features Tonhub is missing. It's  pathetic. I could just go a screen for screen calling you out on copying Tonhub. It is obvious that it's just a repo copy that you've changed in some ways. But you can't even admit that. Instead you lie and spill dirt on Tonhub and other wallets in the ecosystem claiming to be superior.

**Comment by tonsafe** [comment]
No. Go read it again!
We see no current merit in changing our roadmap by going open source before recovering investment, other than enabling you to copy TonSafe.

**Comment by dvlkv** [comment]
@tonsafe, looks like we won't come up with a healthy conversation. I tried.

@tolya-yanot what do you think about @tonsafe response?

**Comment by tolya-yanot** [comment]
@tonsafe @dvlkv We wouldn't want to settle such disputes, but something has to be done.

Since you are both contributors of the TON ecosystem, we consider both views.

Similarity of UI and source code - we are not a court to decide whether someone is infringing intellectual rights or not. Even if the TonSafe source code were open source we would not and should not compare it to the TonHub source code and decide whether it violates the license or not. There are other organizations for that.

We can only rely on obvious and literal facts.

We see that TonSafe uses the *.tonhubapi.com APIs, and Dan as a representative of TonHub is against such use.

On that basis, the decision is as follows:

We temporarily remove TonSafe from the list until the following is done:

1) TonSafe settles the dispute with TonHub on its own

Or

2) TonSafe will run its own instance of api-v4 (api-v4 is under the MIT license) and use its own instance in wallet. By this action TonSafe will show that TonSafe is not just TonHub copy, and will also eliminate objective contradiction with TonHub of using *.tonhubapi.com.
It's good for TonSafe anyway. It's funny that this hasn't been done before, given that you have a long history of claims against each other.

TON Connect 2.0 is still becoming a network-wide standard, so now is a good time to solve this issue.
